export const types = {
    //login
    POST_USER_CREDENTIALS: "POST_USER_CREDENTIALS",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_ERROR: "LOGIN_ERROR",

    //Logout
    USER_LOGOUT: "USER_LOGOUT",
    USER_LOGOUT_SUCCESS: "USER_LOGOUT_SUCCESS",
    USER_LOGOUT_ERROR: "USER_LOGOUT_ERROR",

    //clear login state
    CLEAR_LOGIN_STATE: "CLEAR_LOGIN_STATE",
    
};
